// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: biconom/type/sort.proto

package sort_pb

import (
	limit "github.com/biconom/go-genproto/biconom/type/limit"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sort_Side int32

const (
	Sort_ASC  Sort_Side = 0 // в порядке возрастания (от меньшего к большему)
	Sort_DESC Sort_Side = 1 // в порядке убывания (от большего к меньшему)
)

// Enum value maps for Sort_Side.
var (
	Sort_Side_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Sort_Side_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Sort_Side) Enum() *Sort_Side {
	p := new(Sort_Side)
	*p = x
	return p
}

func (x Sort_Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort_Side) Descriptor() protoreflect.EnumDescriptor {
	return file_biconom_type_sort_proto_enumTypes[0].Descriptor()
}

func (Sort_Side) Type() protoreflect.EnumType {
	return &file_biconom_type_sort_proto_enumTypes[0]
}

func (x Sort_Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort_Side.Descriptor instead.
func (Sort_Side) EnumDescriptor() ([]byte, []int) {
	return file_biconom_type_sort_proto_rawDescGZIP(), []int{0, 0}
}

type Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Side  Sort_Side    `protobuf:"varint,1,opt,name=side,proto3,enum=biconom.type.Sort_Side" json:"side,omitempty"` // направление сортировки
	Limit *limit.Limit `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // лимит возвращаемых записей (min:1)
}

func (x *Sort) Reset() {
	*x = Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_sort_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_sort_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_biconom_type_sort_proto_rawDescGZIP(), []int{0}
}

func (x *Sort) GetSide() Sort_Side {
	if x != nil {
		return x.Side
	}
	return Sort_ASC
}

func (x *Sort) GetLimit() *limit.Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

var File_biconom_type_sort_proto protoreflect.FileDescriptor

var file_biconom_type_sort_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x73,
	0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x69, 0x63, 0x6f, 0x6e,
	0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x18, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x79, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x73, 0x69, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f,
	0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x2e, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x19, 0x0a, 0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x43,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e,
	0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x73, 0x6f, 0x72, 0x74,
	0x3b, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biconom_type_sort_proto_rawDescOnce sync.Once
	file_biconom_type_sort_proto_rawDescData = file_biconom_type_sort_proto_rawDesc
)

func file_biconom_type_sort_proto_rawDescGZIP() []byte {
	file_biconom_type_sort_proto_rawDescOnce.Do(func() {
		file_biconom_type_sort_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconom_type_sort_proto_rawDescData)
	})
	return file_biconom_type_sort_proto_rawDescData
}

var file_biconom_type_sort_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_biconom_type_sort_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_biconom_type_sort_proto_goTypes = []interface{}{
	(Sort_Side)(0),      // 0: biconom.type.Sort.Side
	(*Sort)(nil),        // 1: biconom.type.Sort
	(*limit.Limit)(nil), // 2: biconom.type.Limit
}
var file_biconom_type_sort_proto_depIdxs = []int32{
	0, // 0: biconom.type.Sort.side:type_name -> biconom.type.Sort.Side
	2, // 1: biconom.type.Sort.limit:type_name -> biconom.type.Limit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_biconom_type_sort_proto_init() }
func file_biconom_type_sort_proto_init() {
	if File_biconom_type_sort_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconom_type_sort_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconom_type_sort_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconom_type_sort_proto_goTypes,
		DependencyIndexes: file_biconom_type_sort_proto_depIdxs,
		EnumInfos:         file_biconom_type_sort_proto_enumTypes,
		MessageInfos:      file_biconom_type_sort_proto_msgTypes,
	}.Build()
	File_biconom_type_sort_proto = out.File
	file_biconom_type_sort_proto_rawDesc = nil
	file_biconom_type_sort_proto_goTypes = nil
	file_biconom_type_sort_proto_depIdxs = nil
}
