// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: biconom/type/rank_system.proto

package rank_system_pb

import (
	condition "github.com/biconom/go-genproto/biconom/type/condition"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RankSystem_Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Ranks  []*RankSystem_Rank `protobuf:"bytes,2,rep,name=ranks,proto3" json:"ranks,omitempty"`
}

func (x *RankSystem) Reset() {
	*x = RankSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem) ProtoMessage() {}

func (x *RankSystem) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem.ProtoReflect.Descriptor instead.
func (*RankSystem) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0}
}

func (x *RankSystem) GetHeader() *RankSystem_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RankSystem) GetRanks() []*RankSystem_Rank {
	if x != nil {
		return x.Ranks
	}
	return nil
}

type RankSystem_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UniqueField:
	//	*RankSystem_ID_RankSystemId
	//	*RankSystem_ID_RankSystemName
	UniqueField isRankSystem_ID_UniqueField `protobuf_oneof:"unique_field"`
}

func (x *RankSystem_ID) Reset() {
	*x = RankSystem_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_ID) ProtoMessage() {}

func (x *RankSystem_ID) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_ID.ProtoReflect.Descriptor instead.
func (*RankSystem_ID) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 0}
}

func (m *RankSystem_ID) GetUniqueField() isRankSystem_ID_UniqueField {
	if m != nil {
		return m.UniqueField
	}
	return nil
}

func (x *RankSystem_ID) GetRankSystemId() uint32 {
	if x, ok := x.GetUniqueField().(*RankSystem_ID_RankSystemId); ok {
		return x.RankSystemId
	}
	return 0
}

func (x *RankSystem_ID) GetRankSystemName() string {
	if x, ok := x.GetUniqueField().(*RankSystem_ID_RankSystemName); ok {
		return x.RankSystemName
	}
	return ""
}

type isRankSystem_ID_UniqueField interface {
	isRankSystem_ID_UniqueField()
}

type RankSystem_ID_RankSystemId struct {
	RankSystemId uint32 `protobuf:"varint,1,opt,name=rank_system_id,json=rankSystemId,proto3,oneof"`
}

type RankSystem_ID_RankSystemName struct {
	RankSystemName string `protobuf:"bytes,2,opt,name=rank_system_name,json=rankSystemName,proto3,oneof"`
}

func (*RankSystem_ID_RankSystemId) isRankSystem_ID_UniqueField() {}

func (*RankSystem_ID_RankSystemName) isRankSystem_ID_UniqueField() {}

type RankSystem_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankSystemId   uint32 `protobuf:"varint,1,opt,name=rank_system_id,json=rankSystemId,proto3" json:"rank_system_id,omitempty"`
	RankSystemName string `protobuf:"bytes,2,opt,name=rank_system_name,json=rankSystemName,proto3" json:"rank_system_name,omitempty"`
	Published      bool   `protobuf:"varint,3,opt,name=published,proto3" json:"published,omitempty"`
}

func (x *RankSystem_Header) Reset() {
	*x = RankSystem_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Header) ProtoMessage() {}

func (x *RankSystem_Header) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Header.ProtoReflect.Descriptor instead.
func (*RankSystem_Header) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RankSystem_Header) GetRankSystemId() uint32 {
	if x != nil {
		return x.RankSystemId
	}
	return 0
}

func (x *RankSystem_Header) GetRankSystemName() string {
	if x != nil {
		return x.RankSystemName
	}
	return ""
}

func (x *RankSystem_Header) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

type RankSystem_Rank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header            *RankSystem_Rank_Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ConditionTemplate *condition.Condition_Template `protobuf:"bytes,2,opt,name=condition_template,json=conditionTemplate,proto3" json:"condition_template,omitempty"`
}

func (x *RankSystem_Rank) Reset() {
	*x = RankSystem_Rank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Rank) ProtoMessage() {}

func (x *RankSystem_Rank) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Rank.ProtoReflect.Descriptor instead.
func (*RankSystem_Rank) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RankSystem_Rank) GetHeader() *RankSystem_Rank_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RankSystem_Rank) GetConditionTemplate() *condition.Condition_Template {
	if x != nil {
		return x.ConditionTemplate
	}
	return nil
}

type RankSystem_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RankSystem_Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Rank   *RankSystem_Rank   `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *RankSystem_Option) Reset() {
	*x = RankSystem_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Option) ProtoMessage() {}

func (x *RankSystem_Option) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Option.ProtoReflect.Descriptor instead.
func (*RankSystem_Option) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 3}
}

func (x *RankSystem_Option) GetHeader() *RankSystem_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RankSystem_Option) GetRank() *RankSystem_Rank {
	if x != nil {
		return x.Rank
	}
	return nil
}

type RankSystem_Rank_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UniqueField:
	//	*RankSystem_Rank_ID_RankId
	//	*RankSystem_Rank_ID_RankOption
	UniqueField isRankSystem_Rank_ID_UniqueField `protobuf_oneof:"unique_field"`
}

func (x *RankSystem_Rank_ID) Reset() {
	*x = RankSystem_Rank_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Rank_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Rank_ID) ProtoMessage() {}

func (x *RankSystem_Rank_ID) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Rank_ID.ProtoReflect.Descriptor instead.
func (*RankSystem_Rank_ID) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (m *RankSystem_Rank_ID) GetUniqueField() isRankSystem_Rank_ID_UniqueField {
	if m != nil {
		return m.UniqueField
	}
	return nil
}

func (x *RankSystem_Rank_ID) GetRankId() uint32 {
	if x, ok := x.GetUniqueField().(*RankSystem_Rank_ID_RankId); ok {
		return x.RankId
	}
	return 0
}

func (x *RankSystem_Rank_ID) GetRankOption() *RankSystem_Rank_ID_Option {
	if x, ok := x.GetUniqueField().(*RankSystem_Rank_ID_RankOption); ok {
		return x.RankOption
	}
	return nil
}

type isRankSystem_Rank_ID_UniqueField interface {
	isRankSystem_Rank_ID_UniqueField()
}

type RankSystem_Rank_ID_RankId struct {
	RankId uint32 `protobuf:"varint,1,opt,name=rank_id,json=rankId,proto3,oneof"`
}

type RankSystem_Rank_ID_RankOption struct {
	RankOption *RankSystem_Rank_ID_Option `protobuf:"bytes,2,opt,name=rank_option,json=rankOption,proto3,oneof"`
}

func (*RankSystem_Rank_ID_RankId) isRankSystem_Rank_ID_UniqueField() {}

func (*RankSystem_Rank_ID_RankOption) isRankSystem_Rank_ID_UniqueField() {}

type RankSystem_Rank_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankId   uint32 `protobuf:"varint,1,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	RankName string `protobuf:"bytes,2,opt,name=rank_name,json=rankName,proto3" json:"rank_name,omitempty"`
	Stars    uint32 `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
}

func (x *RankSystem_Rank_Header) Reset() {
	*x = RankSystem_Rank_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Rank_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Rank_Header) ProtoMessage() {}

func (x *RankSystem_Rank_Header) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Rank_Header.ProtoReflect.Descriptor instead.
func (*RankSystem_Rank_Header) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *RankSystem_Rank_Header) GetRankId() uint32 {
	if x != nil {
		return x.RankId
	}
	return 0
}

func (x *RankSystem_Rank_Header) GetRankName() string {
	if x != nil {
		return x.RankName
	}
	return ""
}

func (x *RankSystem_Rank_Header) GetStars() uint32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

type RankSystem_Rank_ID_Inner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UniqueField:
	//	*RankSystem_Rank_ID_Inner_RankName
	//	*RankSystem_Rank_ID_Inner_RankStars
	UniqueField isRankSystem_Rank_ID_Inner_UniqueField `protobuf_oneof:"unique_field"`
}

func (x *RankSystem_Rank_ID_Inner) Reset() {
	*x = RankSystem_Rank_ID_Inner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Rank_ID_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Rank_ID_Inner) ProtoMessage() {}

func (x *RankSystem_Rank_ID_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Rank_ID_Inner.ProtoReflect.Descriptor instead.
func (*RankSystem_Rank_ID_Inner) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 2, 0, 0}
}

func (m *RankSystem_Rank_ID_Inner) GetUniqueField() isRankSystem_Rank_ID_Inner_UniqueField {
	if m != nil {
		return m.UniqueField
	}
	return nil
}

func (x *RankSystem_Rank_ID_Inner) GetRankName() string {
	if x, ok := x.GetUniqueField().(*RankSystem_Rank_ID_Inner_RankName); ok {
		return x.RankName
	}
	return ""
}

func (x *RankSystem_Rank_ID_Inner) GetRankStars() uint32 {
	if x, ok := x.GetUniqueField().(*RankSystem_Rank_ID_Inner_RankStars); ok {
		return x.RankStars
	}
	return 0
}

type isRankSystem_Rank_ID_Inner_UniqueField interface {
	isRankSystem_Rank_ID_Inner_UniqueField()
}

type RankSystem_Rank_ID_Inner_RankName struct {
	RankName string `protobuf:"bytes,1,opt,name=rank_name,json=rankName,proto3,oneof"`
}

type RankSystem_Rank_ID_Inner_RankStars struct {
	RankStars uint32 `protobuf:"varint,2,opt,name=rank_stars,json=rankStars,proto3,oneof"`
}

func (*RankSystem_Rank_ID_Inner_RankName) isRankSystem_Rank_ID_Inner_UniqueField() {}

func (*RankSystem_Rank_ID_Inner_RankStars) isRankSystem_Rank_ID_Inner_UniqueField() {}

type RankSystem_Rank_ID_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankSystem *RankSystem_ID            `protobuf:"bytes,1,opt,name=rank_system,json=rankSystem,proto3" json:"rank_system,omitempty"`
	Rank       *RankSystem_Rank_ID_Inner `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *RankSystem_Rank_ID_Option) Reset() {
	*x = RankSystem_Rank_ID_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_system_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankSystem_Rank_ID_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankSystem_Rank_ID_Option) ProtoMessage() {}

func (x *RankSystem_Rank_ID_Option) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_system_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankSystem_Rank_ID_Option.ProtoReflect.Descriptor instead.
func (*RankSystem_Rank_ID_Option) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_system_proto_rawDescGZIP(), []int{0, 2, 0, 1}
}

func (x *RankSystem_Rank_ID_Option) GetRankSystem() *RankSystem_ID {
	if x != nil {
		return x.RankSystem
	}
	return nil
}

func (x *RankSystem_Rank_ID_Option) GetRank() *RankSystem_Rank_ID_Inner {
	if x != nil {
		return x.Rank
	}
	return nil
}

var File_biconom_type_rank_system_proto protoreflect.FileDescriptor

var file_biconom_type_rank_system_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x72,
	0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x1c,
	0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x08, 0x0a,
	0x0a, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x37, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x69,
	0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x61,
	0x6e, 0x6b, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x1a, 0x68, 0x0a, 0x02, 0x49, 0x44, 0x12,
	0x26, 0x0a, 0x0e, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x6b, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x61, 0x6e, 0x6b, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x1a, 0x76, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x0e, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72,
	0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x1a, 0xc7, 0x04, 0x0a, 0x04,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x3c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x4f, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x11, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x1a, 0xd9, 0x02, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x61,
	0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x72,
	0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x63,
	0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x49, 0x44, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x6b, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x57, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x61,
	0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x72, 0x61, 0x6e,
	0x6b, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x09, 0x72, 0x61, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x72, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x75, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x82, 0x01, 0x0a, 0x06, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x63,
	0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x44, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x12, 0x3a, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x61, 0x6e, 0x6b,
	0x2e, 0x49, 0x44, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x42,
	0x0e, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x1a,
	0x54, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x61, 0x6e,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x6b,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x73, 0x1a, 0x74, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x37, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x42, 0x48, 0x5a, 0x46, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69,
	0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x3b, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biconom_type_rank_system_proto_rawDescOnce sync.Once
	file_biconom_type_rank_system_proto_rawDescData = file_biconom_type_rank_system_proto_rawDesc
)

func file_biconom_type_rank_system_proto_rawDescGZIP() []byte {
	file_biconom_type_rank_system_proto_rawDescOnce.Do(func() {
		file_biconom_type_rank_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconom_type_rank_system_proto_rawDescData)
	})
	return file_biconom_type_rank_system_proto_rawDescData
}

var file_biconom_type_rank_system_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_biconom_type_rank_system_proto_goTypes = []interface{}{
	(*RankSystem)(nil),                   // 0: biconom.type.RankSystem
	(*RankSystem_ID)(nil),                // 1: biconom.type.RankSystem.ID
	(*RankSystem_Header)(nil),            // 2: biconom.type.RankSystem.Header
	(*RankSystem_Rank)(nil),              // 3: biconom.type.RankSystem.Rank
	(*RankSystem_Option)(nil),            // 4: biconom.type.RankSystem.Option
	(*RankSystem_Rank_ID)(nil),           // 5: biconom.type.RankSystem.Rank.ID
	(*RankSystem_Rank_Header)(nil),       // 6: biconom.type.RankSystem.Rank.Header
	(*RankSystem_Rank_ID_Inner)(nil),     // 7: biconom.type.RankSystem.Rank.ID.Inner
	(*RankSystem_Rank_ID_Option)(nil),    // 8: biconom.type.RankSystem.Rank.ID.Option
	(*condition.Condition_Template)(nil), // 9: biconom.type.Condition.Template
}
var file_biconom_type_rank_system_proto_depIdxs = []int32{
	2, // 0: biconom.type.RankSystem.header:type_name -> biconom.type.RankSystem.Header
	3, // 1: biconom.type.RankSystem.ranks:type_name -> biconom.type.RankSystem.Rank
	6, // 2: biconom.type.RankSystem.Rank.header:type_name -> biconom.type.RankSystem.Rank.Header
	9, // 3: biconom.type.RankSystem.Rank.condition_template:type_name -> biconom.type.Condition.Template
	2, // 4: biconom.type.RankSystem.Option.header:type_name -> biconom.type.RankSystem.Header
	3, // 5: biconom.type.RankSystem.Option.rank:type_name -> biconom.type.RankSystem.Rank
	8, // 6: biconom.type.RankSystem.Rank.ID.rank_option:type_name -> biconom.type.RankSystem.Rank.ID.Option
	1, // 7: biconom.type.RankSystem.Rank.ID.Option.rank_system:type_name -> biconom.type.RankSystem.ID
	7, // 8: biconom.type.RankSystem.Rank.ID.Option.rank:type_name -> biconom.type.RankSystem.Rank.ID.Inner
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_biconom_type_rank_system_proto_init() }
func file_biconom_type_rank_system_proto_init() {
	if File_biconom_type_rank_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconom_type_rank_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Rank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Rank_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Rank_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Rank_ID_Inner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_system_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankSystem_Rank_ID_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_biconom_type_rank_system_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*RankSystem_ID_RankSystemId)(nil),
		(*RankSystem_ID_RankSystemName)(nil),
	}
	file_biconom_type_rank_system_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*RankSystem_Rank_ID_RankId)(nil),
		(*RankSystem_Rank_ID_RankOption)(nil),
	}
	file_biconom_type_rank_system_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*RankSystem_Rank_ID_Inner_RankName)(nil),
		(*RankSystem_Rank_ID_Inner_RankStars)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconom_type_rank_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconom_type_rank_system_proto_goTypes,
		DependencyIndexes: file_biconom_type_rank_system_proto_depIdxs,
		MessageInfos:      file_biconom_type_rank_system_proto_msgTypes,
	}.Build()
	File_biconom_type_rank_system_proto = out.File
	file_biconom_type_rank_system_proto_rawDesc = nil
	file_biconom_type_rank_system_proto_goTypes = nil
	file_biconom_type_rank_system_proto_depIdxs = nil
}
