// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: client/confirmation/v1/confirmation.proto

package service_client_confirmation_pb

import (
	context "context"
	confirmation "github.com/biconom/go-genproto/type/confirmation"
	filter "github.com/biconom/go-genproto/type/filter"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfirmationClient is the client API for Confirmation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfirmationClient interface {
	GetById(ctx context.Context, in *confirmation.Confirmation_Id, opts ...grpc.CallOption) (*confirmation.Confirmation, error)
	GetByMethod(ctx context.Context, in *confirmation.Confirmation_Method, opts ...grpc.CallOption) (*confirmation.Confirmation, error)
	GenerateOneTimePassword(ctx context.Context, in *GenerateOneTimePasswordRequest, opts ...grpc.CallOption) (*confirmation.Confirmation_Field_Notification, error)
	Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
	Cancel(ctx context.Context, in *confirmation.Confirmation_Id, opts ...grpc.CallOption) (*emptypb.Empty, error)
	List(ctx context.Context, in *filter.Filter, opts ...grpc.CallOption) (Confirmation_ListClient, error)
	LogsById(ctx context.Context, in *confirmation.Confirmation_Id, opts ...grpc.CallOption) (Confirmation_LogsByIdClient, error)
}

type confirmationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfirmationClient(cc grpc.ClientConnInterface) ConfirmationClient {
	return &confirmationClient{cc}
}

func (c *confirmationClient) GetById(ctx context.Context, in *confirmation.Confirmation_Id, opts ...grpc.CallOption) (*confirmation.Confirmation, error) {
	out := new(confirmation.Confirmation)
	err := c.cc.Invoke(ctx, "/biconom.client.confirmation.v1.Confirmation/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationClient) GetByMethod(ctx context.Context, in *confirmation.Confirmation_Method, opts ...grpc.CallOption) (*confirmation.Confirmation, error) {
	out := new(confirmation.Confirmation)
	err := c.cc.Invoke(ctx, "/biconom.client.confirmation.v1.Confirmation/GetByMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationClient) GenerateOneTimePassword(ctx context.Context, in *GenerateOneTimePasswordRequest, opts ...grpc.CallOption) (*confirmation.Confirmation_Field_Notification, error) {
	out := new(confirmation.Confirmation_Field_Notification)
	err := c.cc.Invoke(ctx, "/biconom.client.confirmation.v1.Confirmation/GenerateOneTimePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationClient) Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, "/biconom.client.confirmation.v1.Confirmation/Confirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationClient) Cancel(ctx context.Context, in *confirmation.Confirmation_Id, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/biconom.client.confirmation.v1.Confirmation/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *confirmationClient) List(ctx context.Context, in *filter.Filter, opts ...grpc.CallOption) (Confirmation_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &Confirmation_ServiceDesc.Streams[0], "/biconom.client.confirmation.v1.Confirmation/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &confirmationListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Confirmation_ListClient interface {
	Recv() (*confirmation.Confirmation, error)
	grpc.ClientStream
}

type confirmationListClient struct {
	grpc.ClientStream
}

func (x *confirmationListClient) Recv() (*confirmation.Confirmation, error) {
	m := new(confirmation.Confirmation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *confirmationClient) LogsById(ctx context.Context, in *confirmation.Confirmation_Id, opts ...grpc.CallOption) (Confirmation_LogsByIdClient, error) {
	stream, err := c.cc.NewStream(ctx, &Confirmation_ServiceDesc.Streams[1], "/biconom.client.confirmation.v1.Confirmation/LogsById", opts...)
	if err != nil {
		return nil, err
	}
	x := &confirmationLogsByIdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Confirmation_LogsByIdClient interface {
	Recv() (*confirmation.Confirmation_Log, error)
	grpc.ClientStream
}

type confirmationLogsByIdClient struct {
	grpc.ClientStream
}

func (x *confirmationLogsByIdClient) Recv() (*confirmation.Confirmation_Log, error) {
	m := new(confirmation.Confirmation_Log)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConfirmationServer is the server API for Confirmation service.
// All implementations must embed UnimplementedConfirmationServer
// for forward compatibility
type ConfirmationServer interface {
	GetById(context.Context, *confirmation.Confirmation_Id) (*confirmation.Confirmation, error)
	GetByMethod(context.Context, *confirmation.Confirmation_Method) (*confirmation.Confirmation, error)
	GenerateOneTimePassword(context.Context, *GenerateOneTimePasswordRequest) (*confirmation.Confirmation_Field_Notification, error)
	Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	Cancel(context.Context, *confirmation.Confirmation_Id) (*emptypb.Empty, error)
	List(*filter.Filter, Confirmation_ListServer) error
	LogsById(*confirmation.Confirmation_Id, Confirmation_LogsByIdServer) error
	mustEmbedUnimplementedConfirmationServer()
}

// UnimplementedConfirmationServer must be embedded to have forward compatible implementations.
type UnimplementedConfirmationServer struct {
}

func (UnimplementedConfirmationServer) GetById(context.Context, *confirmation.Confirmation_Id) (*confirmation.Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedConfirmationServer) GetByMethod(context.Context, *confirmation.Confirmation_Method) (*confirmation.Confirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByMethod not implemented")
}
func (UnimplementedConfirmationServer) GenerateOneTimePassword(context.Context, *GenerateOneTimePasswordRequest) (*confirmation.Confirmation_Field_Notification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateOneTimePassword not implemented")
}
func (UnimplementedConfirmationServer) Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedConfirmationServer) Cancel(context.Context, *confirmation.Confirmation_Id) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedConfirmationServer) List(*filter.Filter, Confirmation_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConfirmationServer) LogsById(*confirmation.Confirmation_Id, Confirmation_LogsByIdServer) error {
	return status.Errorf(codes.Unimplemented, "method LogsById not implemented")
}
func (UnimplementedConfirmationServer) mustEmbedUnimplementedConfirmationServer() {}

// UnsafeConfirmationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfirmationServer will
// result in compilation errors.
type UnsafeConfirmationServer interface {
	mustEmbedUnimplementedConfirmationServer()
}

func RegisterConfirmationServer(s grpc.ServiceRegistrar, srv ConfirmationServer) {
	s.RegisterService(&Confirmation_ServiceDesc, srv)
}

func _Confirmation_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(confirmation.Confirmation_Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biconom.client.confirmation.v1.Confirmation/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServer).GetById(ctx, req.(*confirmation.Confirmation_Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Confirmation_GetByMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(confirmation.Confirmation_Method)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServer).GetByMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biconom.client.confirmation.v1.Confirmation/GetByMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServer).GetByMethod(ctx, req.(*confirmation.Confirmation_Method))
	}
	return interceptor(ctx, in, info, handler)
}

func _Confirmation_GenerateOneTimePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateOneTimePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServer).GenerateOneTimePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biconom.client.confirmation.v1.Confirmation/GenerateOneTimePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServer).GenerateOneTimePassword(ctx, req.(*GenerateOneTimePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Confirmation_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biconom.client.confirmation.v1.Confirmation/Confirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServer).Confirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Confirmation_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(confirmation.Confirmation_Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biconom.client.confirmation.v1.Confirmation/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServer).Cancel(ctx, req.(*confirmation.Confirmation_Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Confirmation_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(filter.Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfirmationServer).List(m, &confirmationListServer{stream})
}

type Confirmation_ListServer interface {
	Send(*confirmation.Confirmation) error
	grpc.ServerStream
}

type confirmationListServer struct {
	grpc.ServerStream
}

func (x *confirmationListServer) Send(m *confirmation.Confirmation) error {
	return x.ServerStream.SendMsg(m)
}

func _Confirmation_LogsById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(confirmation.Confirmation_Id)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfirmationServer).LogsById(m, &confirmationLogsByIdServer{stream})
}

type Confirmation_LogsByIdServer interface {
	Send(*confirmation.Confirmation_Log) error
	grpc.ServerStream
}

type confirmationLogsByIdServer struct {
	grpc.ServerStream
}

func (x *confirmationLogsByIdServer) Send(m *confirmation.Confirmation_Log) error {
	return x.ServerStream.SendMsg(m)
}

// Confirmation_ServiceDesc is the grpc.ServiceDesc for Confirmation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Confirmation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biconom.client.confirmation.v1.Confirmation",
	HandlerType: (*ConfirmationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _Confirmation_GetById_Handler,
		},
		{
			MethodName: "GetByMethod",
			Handler:    _Confirmation_GetByMethod_Handler,
		},
		{
			MethodName: "GenerateOneTimePassword",
			Handler:    _Confirmation_GenerateOneTimePassword_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _Confirmation_Confirm_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Confirmation_Cancel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Confirmation_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LogsById",
			Handler:       _Confirmation_LogsById_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "client/confirmation/v1/confirmation.proto",
}
