// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: biconom/type/rank.proto

package rank_pb

import (
	condition "github.com/biconom/go-genproto/biconom/type/condition"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header          *Rank_Header               `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ConditionBucket *condition.ConditionBucket `protobuf:"bytes,2,opt,name=condition_bucket,json=conditionBucket,proto3" json:"condition_bucket,omitempty"`
}

func (x *Rank) Reset() {
	*x = Rank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_proto_rawDescGZIP(), []int{0}
}

func (x *Rank) GetHeader() *Rank_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Rank) GetConditionBucket() *condition.ConditionBucket {
	if x != nil {
		return x.ConditionBucket
	}
	return nil
}

type RankBucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RankBucket_Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Ranks  []*Rank            `protobuf:"bytes,2,rep,name=ranks,proto3" json:"ranks,omitempty"`
}

func (x *RankBucket) Reset() {
	*x = RankBucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankBucket) ProtoMessage() {}

func (x *RankBucket) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankBucket.ProtoReflect.Descriptor instead.
func (*RankBucket) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_proto_rawDescGZIP(), []int{1}
}

func (x *RankBucket) GetHeader() *RankBucket_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RankBucket) GetRanks() []*Rank {
	if x != nil {
		return x.Ranks
	}
	return nil
}

type Rank_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UniqueField:
	//	*Rank_Id_RankId
	//	*Rank_Id_RankName
	UniqueField isRank_Id_UniqueField `protobuf_oneof:"unique_field"`
}

func (x *Rank_Id) Reset() {
	*x = Rank_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank_Id) ProtoMessage() {}

func (x *Rank_Id) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank_Id.ProtoReflect.Descriptor instead.
func (*Rank_Id) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_proto_rawDescGZIP(), []int{0, 0}
}

func (m *Rank_Id) GetUniqueField() isRank_Id_UniqueField {
	if m != nil {
		return m.UniqueField
	}
	return nil
}

func (x *Rank_Id) GetRankId() uint32 {
	if x, ok := x.GetUniqueField().(*Rank_Id_RankId); ok {
		return x.RankId
	}
	return 0
}

func (x *Rank_Id) GetRankName() uint32 {
	if x, ok := x.GetUniqueField().(*Rank_Id_RankName); ok {
		return x.RankName
	}
	return 0
}

type isRank_Id_UniqueField interface {
	isRank_Id_UniqueField()
}

type Rank_Id_RankId struct {
	RankId uint32 `protobuf:"varint,1,opt,name=rank_id,json=rankId,proto3,oneof"`
}

type Rank_Id_RankName struct {
	RankName uint32 `protobuf:"varint,2,opt,name=rank_name,json=rankName,proto3,oneof"`
}

func (*Rank_Id_RankId) isRank_Id_UniqueField() {}

func (*Rank_Id_RankName) isRank_Id_UniqueField() {}

type Rank_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankId   uint32 `protobuf:"varint,1,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	RankName uint32 `protobuf:"varint,2,opt,name=rank_name,json=rankName,proto3" json:"rank_name,omitempty"`
}

func (x *Rank_Header) Reset() {
	*x = Rank_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank_Header) ProtoMessage() {}

func (x *Rank_Header) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank_Header.ProtoReflect.Descriptor instead.
func (*Rank_Header) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Rank_Header) GetRankId() uint32 {
	if x != nil {
		return x.RankId
	}
	return 0
}

func (x *Rank_Header) GetRankName() uint32 {
	if x != nil {
		return x.RankName
	}
	return 0
}

type RankBucket_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UniqueField:
	//	*RankBucket_Id_BucketId
	//	*RankBucket_Id_BucketName
	UniqueField isRankBucket_Id_UniqueField `protobuf_oneof:"unique_field"`
}

func (x *RankBucket_Id) Reset() {
	*x = RankBucket_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankBucket_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankBucket_Id) ProtoMessage() {}

func (x *RankBucket_Id) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankBucket_Id.ProtoReflect.Descriptor instead.
func (*RankBucket_Id) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_proto_rawDescGZIP(), []int{1, 0}
}

func (m *RankBucket_Id) GetUniqueField() isRankBucket_Id_UniqueField {
	if m != nil {
		return m.UniqueField
	}
	return nil
}

func (x *RankBucket_Id) GetBucketId() uint32 {
	if x, ok := x.GetUniqueField().(*RankBucket_Id_BucketId); ok {
		return x.BucketId
	}
	return 0
}

func (x *RankBucket_Id) GetBucketName() string {
	if x, ok := x.GetUniqueField().(*RankBucket_Id_BucketName); ok {
		return x.BucketName
	}
	return ""
}

type isRankBucket_Id_UniqueField interface {
	isRankBucket_Id_UniqueField()
}

type RankBucket_Id_BucketId struct {
	BucketId uint32 `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3,oneof"`
}

type RankBucket_Id_BucketName struct {
	BucketName string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3,oneof"`
}

func (*RankBucket_Id_BucketId) isRankBucket_Id_UniqueField() {}

func (*RankBucket_Id_BucketName) isRankBucket_Id_UniqueField() {}

type RankBucket_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketId   uint32 `protobuf:"varint,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
}

func (x *RankBucket_Header) Reset() {
	*x = RankBucket_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_rank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankBucket_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankBucket_Header) ProtoMessage() {}

func (x *RankBucket_Header) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_rank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankBucket_Header.ProtoReflect.Descriptor instead.
func (*RankBucket_Header) Descriptor() ([]byte, []int) {
	return file_biconom_type_rank_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RankBucket_Header) GetBucketId() uint32 {
	if x != nil {
		return x.BucketId
	}
	return 0
}

func (x *RankBucket_Header) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

var File_biconom_type_rank_proto protoreflect.FileDescriptor

var file_biconom_type_rank_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x72,
	0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x69, 0x63, 0x6f, 0x6e,
	0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x1c, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x31,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x61,
	0x6e, 0x6b, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x48, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x69,
	0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x4e, 0x0a, 0x02, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09,
	0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x3e, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8f, 0x02, 0x0a, 0x0a,
	0x52, 0x61, 0x6e, 0x6b, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x69, 0x63,
	0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x1a, 0x56, 0x0a,
	0x02, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x46, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x3a, 0x5a,
	0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x63, 0x6f,
	0x6e, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x72, 0x61, 0x6e,
	0x6b, 0x3b, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_biconom_type_rank_proto_rawDescOnce sync.Once
	file_biconom_type_rank_proto_rawDescData = file_biconom_type_rank_proto_rawDesc
)

func file_biconom_type_rank_proto_rawDescGZIP() []byte {
	file_biconom_type_rank_proto_rawDescOnce.Do(func() {
		file_biconom_type_rank_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconom_type_rank_proto_rawDescData)
	})
	return file_biconom_type_rank_proto_rawDescData
}

var file_biconom_type_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_biconom_type_rank_proto_goTypes = []interface{}{
	(*Rank)(nil),                      // 0: biconom.type.Rank
	(*RankBucket)(nil),                // 1: biconom.type.RankBucket
	(*Rank_Id)(nil),                   // 2: biconom.type.Rank.Id
	(*Rank_Header)(nil),               // 3: biconom.type.Rank.Header
	(*RankBucket_Id)(nil),             // 4: biconom.type.RankBucket.Id
	(*RankBucket_Header)(nil),         // 5: biconom.type.RankBucket.Header
	(*condition.ConditionBucket)(nil), // 6: biconom.type.ConditionBucket
}
var file_biconom_type_rank_proto_depIdxs = []int32{
	3, // 0: biconom.type.Rank.header:type_name -> biconom.type.Rank.Header
	6, // 1: biconom.type.Rank.condition_bucket:type_name -> biconom.type.ConditionBucket
	5, // 2: biconom.type.RankBucket.header:type_name -> biconom.type.RankBucket.Header
	0, // 3: biconom.type.RankBucket.ranks:type_name -> biconom.type.Rank
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_biconom_type_rank_proto_init() }
func file_biconom_type_rank_proto_init() {
	if File_biconom_type_rank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconom_type_rank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankBucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankBucket_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_rank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankBucket_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_biconom_type_rank_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Rank_Id_RankId)(nil),
		(*Rank_Id_RankName)(nil),
	}
	file_biconom_type_rank_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*RankBucket_Id_BucketId)(nil),
		(*RankBucket_Id_BucketName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconom_type_rank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconom_type_rank_proto_goTypes,
		DependencyIndexes: file_biconom_type_rank_proto_depIdxs,
		MessageInfos:      file_biconom_type_rank_proto_msgTypes,
	}.Build()
	File_biconom_type_rank_proto = out.File
	file_biconom_type_rank_proto_rawDesc = nil
	file_biconom_type_rank_proto_goTypes = nil
	file_biconom_type_rank_proto_depIdxs = nil
}
