// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: biconom/type/condition.proto

package condition_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Template  *Condition_Template  `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Execution *Condition_Execution `protobuf:"bytes,2,opt,name=execution,proto3" json:"execution,omitempty"`
}

func (x *Condition) Reset() {
	*x = Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_condition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_condition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_biconom_type_condition_proto_rawDescGZIP(), []int{0}
}

func (x *Condition) GetTemplate() *Condition_Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Condition) GetExecution() *Condition_Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type Condition_Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionId uint32 `protobuf:"varint,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
}

func (x *Condition_Template) Reset() {
	*x = Condition_Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_condition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Template) ProtoMessage() {}

func (x *Condition_Template) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_condition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Template.ProtoReflect.Descriptor instead.
func (*Condition_Template) Descriptor() ([]byte, []int) {
	return file_biconom_type_condition_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Condition_Template) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

type Condition_Execution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionId uint32 `protobuf:"varint,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	Done        bool   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	DoneAt      uint32 `protobuf:"varint,3,opt,name=done_at,json=doneAt,proto3" json:"done_at,omitempty"`
}

func (x *Condition_Execution) Reset() {
	*x = Condition_Execution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_condition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition_Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Execution) ProtoMessage() {}

func (x *Condition_Execution) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_condition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Execution.ProtoReflect.Descriptor instead.
func (*Condition_Execution) Descriptor() ([]byte, []int) {
	return file_biconom_type_condition_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Condition_Execution) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

func (x *Condition_Execution) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Condition_Execution) GetDoneAt() uint32 {
	if x != nil {
		return x.DoneAt
	}
	return 0
}

type Condition_Template_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionId uint32 `protobuf:"varint,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
}

func (x *Condition_Template_ID) Reset() {
	*x = Condition_Template_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_condition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition_Template_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Template_ID) ProtoMessage() {}

func (x *Condition_Template_ID) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_condition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Template_ID.ProtoReflect.Descriptor instead.
func (*Condition_Template_ID) Descriptor() ([]byte, []int) {
	return file_biconom_type_condition_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Condition_Template_ID) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

type Condition_Execution_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionId uint32 `protobuf:"varint,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
}

func (x *Condition_Execution_ID) Reset() {
	*x = Condition_Execution_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_condition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition_Execution_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Execution_ID) ProtoMessage() {}

func (x *Condition_Execution_ID) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_condition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Execution_ID.ProtoReflect.Descriptor instead.
func (*Condition_Execution_ID) Descriptor() ([]byte, []int) {
	return file_biconom_type_condition_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Condition_Execution_ID) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

var File_biconom_type_condition_proto protoreflect.FileDescriptor

var file_biconom_type_condition_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x22, 0xe9, 0x02, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x08, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62,
	0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x08,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x69,
	0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x56, 0x0a, 0x08, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x27, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x1a, 0x84, 0x01, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x6f, 0x6e, 0x65, 0x5f, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x64, 0x6f, 0x6e, 0x65, 0x41, 0x74, 0x1a,
	0x27, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e,
	0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x3b, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biconom_type_condition_proto_rawDescOnce sync.Once
	file_biconom_type_condition_proto_rawDescData = file_biconom_type_condition_proto_rawDesc
)

func file_biconom_type_condition_proto_rawDescGZIP() []byte {
	file_biconom_type_condition_proto_rawDescOnce.Do(func() {
		file_biconom_type_condition_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconom_type_condition_proto_rawDescData)
	})
	return file_biconom_type_condition_proto_rawDescData
}

var file_biconom_type_condition_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_biconom_type_condition_proto_goTypes = []interface{}{
	(*Condition)(nil),              // 0: biconom.type.Condition
	(*Condition_Template)(nil),     // 1: biconom.type.Condition.Template
	(*Condition_Execution)(nil),    // 2: biconom.type.Condition.Execution
	(*Condition_Template_ID)(nil),  // 3: biconom.type.Condition.Template.ID
	(*Condition_Execution_ID)(nil), // 4: biconom.type.Condition.Execution.ID
}
var file_biconom_type_condition_proto_depIdxs = []int32{
	1, // 0: biconom.type.Condition.template:type_name -> biconom.type.Condition.Template
	2, // 1: biconom.type.Condition.execution:type_name -> biconom.type.Condition.Execution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_biconom_type_condition_proto_init() }
func file_biconom_type_condition_proto_init() {
	if File_biconom_type_condition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconom_type_condition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_condition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition_Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_condition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition_Execution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_condition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition_Template_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_condition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition_Execution_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconom_type_condition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconom_type_condition_proto_goTypes,
		DependencyIndexes: file_biconom_type_condition_proto_depIdxs,
		MessageInfos:      file_biconom_type_condition_proto_msgTypes,
	}.Build()
	File_biconom_type_condition_proto = out.File
	file_biconom_type_condition_proto_rawDesc = nil
	file_biconom_type_condition_proto_goTypes = nil
	file_biconom_type_condition_proto_depIdxs = nil
}
