// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: biconom/type/payment_system.proto

package payment_system_pb

import (
	currency "github.com/biconom/go-genproto/biconom/type/currency"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *PaymentSystem_Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Values []*PaymentSystem_Option_Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *PaymentSystem) Reset() {
	*x = PaymentSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_payment_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSystem) ProtoMessage() {}

func (x *PaymentSystem) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_payment_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSystem.ProtoReflect.Descriptor instead.
func (*PaymentSystem) Descriptor() ([]byte, []int) {
	return file_biconom_type_payment_system_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentSystem) GetHeader() *PaymentSystem_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PaymentSystem) GetValues() []*PaymentSystem_Option_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type PaymentSystem_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UniqueField:
	//	*PaymentSystem_ID_PaymentSystemId
	//	*PaymentSystem_ID_PaymentSystemName
	UniqueField isPaymentSystem_ID_UniqueField `protobuf_oneof:"unique_field"`
}

func (x *PaymentSystem_ID) Reset() {
	*x = PaymentSystem_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_payment_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSystem_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSystem_ID) ProtoMessage() {}

func (x *PaymentSystem_ID) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_payment_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSystem_ID.ProtoReflect.Descriptor instead.
func (*PaymentSystem_ID) Descriptor() ([]byte, []int) {
	return file_biconom_type_payment_system_proto_rawDescGZIP(), []int{0, 0}
}

func (m *PaymentSystem_ID) GetUniqueField() isPaymentSystem_ID_UniqueField {
	if m != nil {
		return m.UniqueField
	}
	return nil
}

func (x *PaymentSystem_ID) GetPaymentSystemId() uint32 {
	if x, ok := x.GetUniqueField().(*PaymentSystem_ID_PaymentSystemId); ok {
		return x.PaymentSystemId
	}
	return 0
}

func (x *PaymentSystem_ID) GetPaymentSystemName() string {
	if x, ok := x.GetUniqueField().(*PaymentSystem_ID_PaymentSystemName); ok {
		return x.PaymentSystemName
	}
	return ""
}

type isPaymentSystem_ID_UniqueField interface {
	isPaymentSystem_ID_UniqueField()
}

type PaymentSystem_ID_PaymentSystemId struct {
	PaymentSystemId uint32 `protobuf:"varint,1,opt,name=payment_system_id,json=paymentSystemId,proto3,oneof"`
}

type PaymentSystem_ID_PaymentSystemName struct {
	PaymentSystemName string `protobuf:"bytes,2,opt,name=payment_system_name,json=paymentSystemName,proto3,oneof"`
}

func (*PaymentSystem_ID_PaymentSystemId) isPaymentSystem_ID_UniqueField() {}

func (*PaymentSystem_ID_PaymentSystemName) isPaymentSystem_ID_UniqueField() {}

type PaymentSystem_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentSystemId   uint32 `protobuf:"varint,1,opt,name=payment_system_id,json=paymentSystemId,proto3" json:"payment_system_id,omitempty"`
	PaymentSystemName string `protobuf:"bytes,2,opt,name=payment_system_name,json=paymentSystemName,proto3" json:"payment_system_name,omitempty"`
	Published         bool   `protobuf:"varint,3,opt,name=published,proto3" json:"published,omitempty"`
}

func (x *PaymentSystem_Header) Reset() {
	*x = PaymentSystem_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_payment_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSystem_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSystem_Header) ProtoMessage() {}

func (x *PaymentSystem_Header) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_payment_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSystem_Header.ProtoReflect.Descriptor instead.
func (*PaymentSystem_Header) Descriptor() ([]byte, []int) {
	return file_biconom_type_payment_system_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PaymentSystem_Header) GetPaymentSystemId() uint32 {
	if x != nil {
		return x.PaymentSystemId
	}
	return 0
}

func (x *PaymentSystem_Header) GetPaymentSystemName() string {
	if x != nil {
		return x.PaymentSystemName
	}
	return ""
}

func (x *PaymentSystem_Header) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

type PaymentSystem_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentSystem *PaymentSystem_Header       `protobuf:"bytes,1,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty"`
	Value         *PaymentSystem_Option_Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PaymentSystem_Option) Reset() {
	*x = PaymentSystem_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_payment_system_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSystem_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSystem_Option) ProtoMessage() {}

func (x *PaymentSystem_Option) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_payment_system_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSystem_Option.ProtoReflect.Descriptor instead.
func (*PaymentSystem_Option) Descriptor() ([]byte, []int) {
	return file_biconom_type_payment_system_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PaymentSystem_Option) GetPaymentSystem() *PaymentSystem_Header {
	if x != nil {
		return x.PaymentSystem
	}
	return nil
}

func (x *PaymentSystem_Option) GetValue() *PaymentSystem_Option_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type PaymentSystem_Option_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentSystem *PaymentSystem_ID     `protobuf:"bytes,1,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty"`
	Currency      *currency.Currency_ID `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *PaymentSystem_Option_ID) Reset() {
	*x = PaymentSystem_Option_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_payment_system_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSystem_Option_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSystem_Option_ID) ProtoMessage() {}

func (x *PaymentSystem_Option_ID) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_payment_system_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSystem_Option_ID.ProtoReflect.Descriptor instead.
func (*PaymentSystem_Option_ID) Descriptor() ([]byte, []int) {
	return file_biconom_type_payment_system_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *PaymentSystem_Option_ID) GetPaymentSystem() *PaymentSystem_ID {
	if x != nil {
		return x.PaymentSystem
	}
	return nil
}

func (x *PaymentSystem_Option_ID) GetCurrency() *currency.Currency_ID {
	if x != nil {
		return x.Currency
	}
	return nil
}

type PaymentSystem_Option_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency  *currency.Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Published bool               `protobuf:"varint,2,opt,name=published,proto3" json:"published,omitempty"`
}

func (x *PaymentSystem_Option_Value) Reset() {
	*x = PaymentSystem_Option_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_payment_system_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentSystem_Option_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSystem_Option_Value) ProtoMessage() {}

func (x *PaymentSystem_Option_Value) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_payment_system_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSystem_Option_Value.ProtoReflect.Descriptor instead.
func (*PaymentSystem_Option_Value) Descriptor() ([]byte, []int) {
	return file_biconom_type_payment_system_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *PaymentSystem_Option_Value) GetCurrency() *currency.Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *PaymentSystem_Option_Value) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

var File_biconom_type_payment_system_proto protoreflect.FileDescriptor

var file_biconom_type_payment_system_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x1a, 0x1b, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe,
	0x05, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x12, 0x3a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62,
	0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x74,
	0x0a, 0x02, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x1a, 0x82, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x1a, 0xf3, 0x02, 0x0a, 0x06, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62,
	0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12,
	0x3e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x82, 0x01, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x45, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x44, 0x52, 0x0d,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x35, 0x0a,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x49, 0x44, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x1a, 0x59, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x32, 0x0a,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x42,
	0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69,
	0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x3b, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biconom_type_payment_system_proto_rawDescOnce sync.Once
	file_biconom_type_payment_system_proto_rawDescData = file_biconom_type_payment_system_proto_rawDesc
)

func file_biconom_type_payment_system_proto_rawDescGZIP() []byte {
	file_biconom_type_payment_system_proto_rawDescOnce.Do(func() {
		file_biconom_type_payment_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconom_type_payment_system_proto_rawDescData)
	})
	return file_biconom_type_payment_system_proto_rawDescData
}

var file_biconom_type_payment_system_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_biconom_type_payment_system_proto_goTypes = []interface{}{
	(*PaymentSystem)(nil),              // 0: biconom.type.PaymentSystem
	(*PaymentSystem_ID)(nil),           // 1: biconom.type.PaymentSystem.ID
	(*PaymentSystem_Header)(nil),       // 2: biconom.type.PaymentSystem.Header
	(*PaymentSystem_Option)(nil),       // 3: biconom.type.PaymentSystem.Option
	(*PaymentSystem_Option_ID)(nil),    // 4: biconom.type.PaymentSystem.Option.ID
	(*PaymentSystem_Option_Value)(nil), // 5: biconom.type.PaymentSystem.Option.Value
	(*currency.Currency_ID)(nil),       // 6: biconom.type.Currency.ID
	(*currency.Currency)(nil),          // 7: biconom.type.Currency
}
var file_biconom_type_payment_system_proto_depIdxs = []int32{
	2, // 0: biconom.type.PaymentSystem.header:type_name -> biconom.type.PaymentSystem.Header
	5, // 1: biconom.type.PaymentSystem.values:type_name -> biconom.type.PaymentSystem.Option.Value
	2, // 2: biconom.type.PaymentSystem.Option.payment_system:type_name -> biconom.type.PaymentSystem.Header
	5, // 3: biconom.type.PaymentSystem.Option.value:type_name -> biconom.type.PaymentSystem.Option.Value
	1, // 4: biconom.type.PaymentSystem.Option.ID.payment_system:type_name -> biconom.type.PaymentSystem.ID
	6, // 5: biconom.type.PaymentSystem.Option.ID.currency:type_name -> biconom.type.Currency.ID
	7, // 6: biconom.type.PaymentSystem.Option.Value.currency:type_name -> biconom.type.Currency
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_biconom_type_payment_system_proto_init() }
func file_biconom_type_payment_system_proto_init() {
	if File_biconom_type_payment_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconom_type_payment_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_payment_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSystem_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_payment_system_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSystem_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_payment_system_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSystem_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_payment_system_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSystem_Option_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_payment_system_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentSystem_Option_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_biconom_type_payment_system_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PaymentSystem_ID_PaymentSystemId)(nil),
		(*PaymentSystem_ID_PaymentSystemName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconom_type_payment_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconom_type_payment_system_proto_goTypes,
		DependencyIndexes: file_biconom_type_payment_system_proto_depIdxs,
		MessageInfos:      file_biconom_type_payment_system_proto_msgTypes,
	}.Build()
	File_biconom_type_payment_system_proto = out.File
	file_biconom_type_payment_system_proto_rawDesc = nil
	file_biconom_type_payment_system_proto_goTypes = nil
	file_biconom_type_payment_system_proto_depIdxs = nil
}
