// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: biconom/type/confirmation.proto

package confirmation_pb

import (
	contact "github.com/biconom/go-genproto/biconom/type/contact"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Confirmation_Status int32

const (
	Confirmation_CREATED  Confirmation_Status = 0
	Confirmation_APPROVED Confirmation_Status = 1
	Confirmation_REJECT   Confirmation_Status = 2
	Confirmation_CANCELED Confirmation_Status = 3
	Confirmation_EXPIRED  Confirmation_Status = 4
)

// Enum value maps for Confirmation_Status.
var (
	Confirmation_Status_name = map[int32]string{
		0: "CREATED",
		1: "APPROVED",
		2: "REJECT",
		3: "CANCELED",
		4: "EXPIRED",
	}
	Confirmation_Status_value = map[string]int32{
		"CREATED":  0,
		"APPROVED": 1,
		"REJECT":   2,
		"CANCELED": 3,
		"EXPIRED":  4,
	}
)

func (x Confirmation_Status) Enum() *Confirmation_Status {
	p := new(Confirmation_Status)
	*p = x
	return p
}

func (x Confirmation_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confirmation_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_biconom_type_confirmation_proto_enumTypes[0].Descriptor()
}

func (Confirmation_Status) Type() protoreflect.EnumType {
	return &file_biconom_type_confirmation_proto_enumTypes[0]
}

func (x Confirmation_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confirmation_Status.Descriptor instead.
func (Confirmation_Status) EnumDescriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 0}
}

type Confirmation_Method_Id int32

const (
	Confirmation_Method_CUSTOM                                   Confirmation_Method_Id = 0
	Confirmation_Method_SIGN_IN                                  Confirmation_Method_Id = 1  // авторизация
	Confirmation_Method_SIGN_UP                                  Confirmation_Method_Id = 2  // регистрация
	Confirmation_Method_SIGN_ATTACH                              Confirmation_Method_Id = 3  // привязать регистрационные данные
	Confirmation_Method_RECOVERY_PASSWORD                        Confirmation_Method_Id = 4  // восстановить пароль
	Confirmation_Method_RECOVERY_GOOGLE_AUTHENTICATOR            Confirmation_Method_Id = 5  // восстановить 2FA
	Confirmation_Method_SET_PROFILE                              Confirmation_Method_Id = 6  // установить персональные данные профиля пользователя
	Confirmation_Method_SET_LOGIN                                Confirmation_Method_Id = 7  // установить логин
	Confirmation_Method_CLEAR_LOGIN                              Confirmation_Method_Id = 8  // очистить поле логин
	Confirmation_Method_SET_LOCALE                               Confirmation_Method_Id = 9  // установить локализацию
	Confirmation_Method_ADD_CONTACT                              Confirmation_Method_Id = 10 // добавить контакт
	Confirmation_Method_DELETE_CONTACT                           Confirmation_Method_Id = 11 // удалить контакт
	Confirmation_Method_CHANGE_PASSWORD                          Confirmation_Method_Id = 12 // изменить пароль
	Confirmation_Method_ACTIVATE_SECURITY_GOOGLE_AUTHENTICATOR   Confirmation_Method_Id = 13 // активировать 2FA
	Confirmation_Method_DEACTIVATE_SECURITY_GOOGLE_AUTHENTICATOR Confirmation_Method_Id = 14 // деактивировать 2FA
)

// Enum value maps for Confirmation_Method_Id.
var (
	Confirmation_Method_Id_name = map[int32]string{
		0:  "CUSTOM",
		1:  "SIGN_IN",
		2:  "SIGN_UP",
		3:  "SIGN_ATTACH",
		4:  "RECOVERY_PASSWORD",
		5:  "RECOVERY_GOOGLE_AUTHENTICATOR",
		6:  "SET_PROFILE",
		7:  "SET_LOGIN",
		8:  "CLEAR_LOGIN",
		9:  "SET_LOCALE",
		10: "ADD_CONTACT",
		11: "DELETE_CONTACT",
		12: "CHANGE_PASSWORD",
		13: "ACTIVATE_SECURITY_GOOGLE_AUTHENTICATOR",
		14: "DEACTIVATE_SECURITY_GOOGLE_AUTHENTICATOR",
	}
	Confirmation_Method_Id_value = map[string]int32{
		"CUSTOM":                                 0,
		"SIGN_IN":                                1,
		"SIGN_UP":                                2,
		"SIGN_ATTACH":                            3,
		"RECOVERY_PASSWORD":                      4,
		"RECOVERY_GOOGLE_AUTHENTICATOR":          5,
		"SET_PROFILE":                            6,
		"SET_LOGIN":                              7,
		"CLEAR_LOGIN":                            8,
		"SET_LOCALE":                             9,
		"ADD_CONTACT":                            10,
		"DELETE_CONTACT":                         11,
		"CHANGE_PASSWORD":                        12,
		"ACTIVATE_SECURITY_GOOGLE_AUTHENTICATOR": 13,
		"DEACTIVATE_SECURITY_GOOGLE_AUTHENTICATOR": 14,
	}
)

func (x Confirmation_Method_Id) Enum() *Confirmation_Method_Id {
	p := new(Confirmation_Method_Id)
	*p = x
	return p
}

func (x Confirmation_Method_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confirmation_Method_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_biconom_type_confirmation_proto_enumTypes[1].Descriptor()
}

func (Confirmation_Method_Id) Type() protoreflect.EnumType {
	return &file_biconom_type_confirmation_proto_enumTypes[1]
}

func (x Confirmation_Method_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confirmation_Method_Id.Descriptor instead.
func (Confirmation_Method_Id) EnumDescriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Confirmation_Field_Type int32

const (
	Confirmation_Field_UNKNOWN                   Confirmation_Field_Type = 0
	Confirmation_Field_PASSWORD                  Confirmation_Field_Type = 1 // пароль
	Confirmation_Field_PASSWORD_NEW              Confirmation_Field_Type = 2 // новый пароль (используется при смене пароля)
	Confirmation_Field_GOOGLE_AUTHENTICATOR_CODE Confirmation_Field_Type = 3 // 2FA код
	Confirmation_Field_CONTACT_CONFIRM_CODE      Confirmation_Field_Type = 4 // подтвердить код отправленный на указанный контакт
	Confirmation_Field_CONTACT_FILL              Confirmation_Field_Type = 5 // заполнить значение контакта (например: sm***el@gmail.com - требуется заполнить поле без маски с звездочками)
)

// Enum value maps for Confirmation_Field_Type.
var (
	Confirmation_Field_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "PASSWORD",
		2: "PASSWORD_NEW",
		3: "GOOGLE_AUTHENTICATOR_CODE",
		4: "CONTACT_CONFIRM_CODE",
		5: "CONTACT_FILL",
	}
	Confirmation_Field_Type_value = map[string]int32{
		"UNKNOWN":                   0,
		"PASSWORD":                  1,
		"PASSWORD_NEW":              2,
		"GOOGLE_AUTHENTICATOR_CODE": 3,
		"CONTACT_CONFIRM_CODE":      4,
		"CONTACT_FILL":              5,
	}
)

func (x Confirmation_Field_Type) Enum() *Confirmation_Field_Type {
	p := new(Confirmation_Field_Type)
	*p = x
	return p
}

func (x Confirmation_Field_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confirmation_Field_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_biconom_type_confirmation_proto_enumTypes[2].Descriptor()
}

func (Confirmation_Field_Type) Type() protoreflect.EnumType {
	return &file_biconom_type_confirmation_proto_enumTypes[2]
}

func (x Confirmation_Field_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confirmation_Field_Type.Descriptor instead.
func (Confirmation_Field_Type) EnumDescriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Confirmation_Field_Status_Id int32

const (
	Confirmation_Field_Status_OK      Confirmation_Field_Status_Id = 0
	Confirmation_Field_Status_EMPTY   Confirmation_Field_Status_Id = 1
	Confirmation_Field_Status_WRONG   Confirmation_Field_Status_Id = 2
	Confirmation_Field_Status_EXPIRED Confirmation_Field_Status_Id = 3
)

// Enum value maps for Confirmation_Field_Status_Id.
var (
	Confirmation_Field_Status_Id_name = map[int32]string{
		0: "OK",
		1: "EMPTY",
		2: "WRONG",
		3: "EXPIRED",
	}
	Confirmation_Field_Status_Id_value = map[string]int32{
		"OK":      0,
		"EMPTY":   1,
		"WRONG":   2,
		"EXPIRED": 3,
	}
)

func (x Confirmation_Field_Status_Id) Enum() *Confirmation_Field_Status_Id {
	p := new(Confirmation_Field_Status_Id)
	*p = x
	return p
}

func (x Confirmation_Field_Status_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confirmation_Field_Status_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_biconom_type_confirmation_proto_enumTypes[3].Descriptor()
}

func (Confirmation_Field_Status_Id) Type() protoreflect.EnumType {
	return &file_biconom_type_confirmation_proto_enumTypes[3]
}

func (x Confirmation_Field_Status_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confirmation_Field_Status_Id.Descriptor instead.
func (Confirmation_Field_Status_Id) EnumDescriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 2, 0, 0}
}

type Confirmation_Log_Event_Type_Id int32

const (
	Confirmation_Log_Event_Type_UNKNOWN Confirmation_Log_Event_Type_Id = 0
)

// Enum value maps for Confirmation_Log_Event_Type_Id.
var (
	Confirmation_Log_Event_Type_Id_name = map[int32]string{
		0: "UNKNOWN",
	}
	Confirmation_Log_Event_Type_Id_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x Confirmation_Log_Event_Type_Id) Enum() *Confirmation_Log_Event_Type_Id {
	p := new(Confirmation_Log_Event_Type_Id)
	*p = x
	return p
}

func (x Confirmation_Log_Event_Type_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confirmation_Log_Event_Type_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_biconom_type_confirmation_proto_enumTypes[4].Descriptor()
}

func (Confirmation_Log_Event_Type_Id) Type() protoreflect.EnumType {
	return &file_biconom_type_confirmation_proto_enumTypes[4]
}

func (x Confirmation_Log_Event_Type_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confirmation_Log_Event_Type_Id.Descriptor instead.
func (Confirmation_Log_Event_Type_Id) EnumDescriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 4, 0, 0, 0}
}

type Confirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MethodId     Confirmation_Method_Id         `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3,enum=biconom.type.Confirmation_Method_Id" json:"method_id,omitempty"`
	StatusId     Confirmation_Status            `protobuf:"varint,3,opt,name=status_id,json=statusId,proto3,enum=biconom.type.Confirmation_Status" json:"status_id,omitempty"`
	CreatedAt    int64                          `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt    int64                          `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ModifiedAt   int64                          `protobuf:"varint,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	CounterLimit uint32                         `protobuf:"varint,7,opt,name=counter_limit,json=counterLimit,proto3" json:"counter_limit,omitempty"`
	CounterValue uint32                         `protobuf:"varint,8,opt,name=counter_value,json=counterValue,proto3" json:"counter_value,omitempty"`
	Fields       map[uint32]*Confirmation_Field `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // map key is "field_id"
	Options      []*Confirmation_Option         `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0}
}

func (x *Confirmation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Confirmation) GetMethodId() Confirmation_Method_Id {
	if x != nil {
		return x.MethodId
	}
	return Confirmation_Method_CUSTOM
}

func (x *Confirmation) GetStatusId() Confirmation_Status {
	if x != nil {
		return x.StatusId
	}
	return Confirmation_CREATED
}

func (x *Confirmation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Confirmation) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Confirmation) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *Confirmation) GetCounterLimit() uint32 {
	if x != nil {
		return x.CounterLimit
	}
	return 0
}

func (x *Confirmation) GetCounterValue() uint32 {
	if x != nil {
		return x.CounterValue
	}
	return 0
}

func (x *Confirmation) GetFields() map[uint32]*Confirmation_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Confirmation) GetOptions() []*Confirmation_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type Confirmation_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Confirmation_Id) Reset() {
	*x = Confirmation_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Id) ProtoMessage() {}

func (x *Confirmation_Id) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Id.ProtoReflect.Descriptor instead.
func (*Confirmation_Id) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Confirmation_Id) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Confirmation_Method struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodId Confirmation_Method_Id `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3,enum=biconom.type.Confirmation_Method_Id" json:"method_id,omitempty"`
}

func (x *Confirmation_Method) Reset() {
	*x = Confirmation_Method{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Method) ProtoMessage() {}

func (x *Confirmation_Method) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Method.ProtoReflect.Descriptor instead.
func (*Confirmation_Method) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Confirmation_Method) GetMethodId() Confirmation_Method_Id {
	if x != nil {
		return x.MethodId
	}
	return Confirmation_Method_CUSTOM
}

type Confirmation_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldId      uint32                           `protobuf:"varint,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`                                        // идентификатор поля
	TypeId       Confirmation_Field_Type          `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3,enum=biconom.type.Confirmation_Field_Type" json:"type_id,omitempty"` // тип поля
	Status       *Confirmation_Field_Status       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                          // статус поля
	Contact      *contact.Contact                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`                                                        // контакт, используется при CONTACT_CONFIRM_CODE и CONTACT_FILL
	Notification *Confirmation_Field_Notification `protobuf:"bytes,5,opt,name=notification,proto3" json:"notification,omitempty"`                                              // используется при CONTACT_CONFIRM_CODE
}

func (x *Confirmation_Field) Reset() {
	*x = Confirmation_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Field) ProtoMessage() {}

func (x *Confirmation_Field) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Field.ProtoReflect.Descriptor instead.
func (*Confirmation_Field) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Confirmation_Field) GetFieldId() uint32 {
	if x != nil {
		return x.FieldId
	}
	return 0
}

func (x *Confirmation_Field) GetTypeId() Confirmation_Field_Type {
	if x != nil {
		return x.TypeId
	}
	return Confirmation_Field_UNKNOWN
}

func (x *Confirmation_Field) GetStatus() *Confirmation_Field_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Confirmation_Field) GetContact() *contact.Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Confirmation_Field) GetNotification() *Confirmation_Field_Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type Confirmation_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldIds []uint32 `protobuf:"varint,1,rep,packed,name=field_ids,json=fieldIds,proto3" json:"field_ids,omitempty"` // список идентификаторов полей "field_id" обязательные для подтверждения формы
}

func (x *Confirmation_Option) Reset() {
	*x = Confirmation_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Option) ProtoMessage() {}

func (x *Confirmation_Option) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Option.ProtoReflect.Descriptor instead.
func (*Confirmation_Option) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Confirmation_Option) GetFieldIds() []uint32 {
	if x != nil {
		return x.FieldIds
	}
	return nil
}

type Confirmation_Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogId     uint32                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	CreatedAt int64                   `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Event     *Confirmation_Log_Event `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *Confirmation_Log) Reset() {
	*x = Confirmation_Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Log) ProtoMessage() {}

func (x *Confirmation_Log) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Log.ProtoReflect.Descriptor instead.
func (*Confirmation_Log) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Confirmation_Log) GetLogId() uint32 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *Confirmation_Log) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Confirmation_Log) GetEvent() *Confirmation_Log_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Confirmation_Field_Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      Confirmation_Field_Status_Id `protobuf:"varint,1,opt,name=id,proto3,enum=biconom.type.Confirmation_Field_Status_Id" json:"id,omitempty"`
	Comment string                       `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Confirmation_Field_Status) Reset() {
	*x = Confirmation_Field_Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Field_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Field_Status) ProtoMessage() {}

func (x *Confirmation_Field_Status) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Field_Status.ProtoReflect.Descriptor instead.
func (*Confirmation_Field_Status) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Confirmation_Field_Status) GetId() Confirmation_Field_Status_Id {
	if x != nil {
		return x.Id
	}
	return Confirmation_Field_Status_OK
}

func (x *Confirmation_Field_Status) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Confirmation_Field_Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextAt       int64  `protobuf:"varint,1,opt,name=next_at,json=nextAt,proto3" json:"next_at,omitempty"`                   // отображает разрешенное время после которого возможно отправить новый код
	CreatedAt    int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // отображает время создания текущего кода
	ExpiresAt    int64  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`          // отображает время после которого отправленный токен будет не валидный
	CounterLimit uint32 `protobuf:"varint,4,opt,name=counter_limit,json=counterLimit,proto3" json:"counter_limit,omitempty"` // отображает лимит доступных уведомлений
	CounterValue uint32 `protobuf:"varint,5,opt,name=counter_value,json=counterValue,proto3" json:"counter_value,omitempty"` // отображает количество отправленных уведомлений с кодом подтверждения
}

func (x *Confirmation_Field_Notification) Reset() {
	*x = Confirmation_Field_Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Field_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Field_Notification) ProtoMessage() {}

func (x *Confirmation_Field_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Field_Notification.ProtoReflect.Descriptor instead.
func (*Confirmation_Field_Notification) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Confirmation_Field_Notification) GetNextAt() int64 {
	if x != nil {
		return x.NextAt
	}
	return 0
}

func (x *Confirmation_Field_Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Confirmation_Field_Notification) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Confirmation_Field_Notification) GetCounterLimit() uint32 {
	if x != nil {
		return x.CounterLimit
	}
	return 0
}

func (x *Confirmation_Field_Notification) GetCounterValue() uint32 {
	if x != nil {
		return x.CounterValue
	}
	return 0
}

type Confirmation_Log_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType Confirmation_Log_Event_Type_Id `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=biconom.type.Confirmation_Log_Event_Type_Id" json:"event_type,omitempty"`
	Data      *anypb.Any                     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Confirmation_Log_Event) Reset() {
	*x = Confirmation_Log_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Log_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Log_Event) ProtoMessage() {}

func (x *Confirmation_Log_Event) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Log_Event.ProtoReflect.Descriptor instead.
func (*Confirmation_Log_Event) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Confirmation_Log_Event) GetEventType() Confirmation_Log_Event_Type_Id {
	if x != nil {
		return x.EventType
	}
	return Confirmation_Log_Event_Type_UNKNOWN
}

func (x *Confirmation_Log_Event) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type Confirmation_Log_Event_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType Confirmation_Log_Event_Type_Id `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=biconom.type.Confirmation_Log_Event_Type_Id" json:"event_type,omitempty"`
}

func (x *Confirmation_Log_Event_Type) Reset() {
	*x = Confirmation_Log_Event_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biconom_type_confirmation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmation_Log_Event_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation_Log_Event_Type) ProtoMessage() {}

func (x *Confirmation_Log_Event_Type) ProtoReflect() protoreflect.Message {
	mi := &file_biconom_type_confirmation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation_Log_Event_Type.ProtoReflect.Descriptor instead.
func (*Confirmation_Log_Event_Type) Descriptor() ([]byte, []int) {
	return file_biconom_type_confirmation_proto_rawDescGZIP(), []int{0, 4, 0, 0}
}

func (x *Confirmation_Log_Event_Type) GetEventType() Confirmation_Log_Event_Type_Id {
	if x != nil {
		return x.EventType
	}
	return Confirmation_Log_Event_Type_UNKNOWN
}

var File_biconom_type_confirmation_proto protoreflect.FileDescriptor

var file_biconom_type_confirmation_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x1a,
	0x1a, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x11, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x69, 0x63,
	0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x49, 0x64,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x3b, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x14, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x98, 0x03, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x41, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x49, 0x64, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x49, 0x64, 0x22, 0xca, 0x02, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x49, 0x47, 0x4e, 0x5f,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x55, 0x50, 0x10,
	0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x48,
	0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x50,
	0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x04, 0x12, 0x21, 0x0a, 0x1d, 0x52, 0x45, 0x43,
	0x4f, 0x56, 0x45, 0x52, 0x59, 0x5f, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x41, 0x55, 0x54,
	0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x45, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x4c, 0x45, 0x41, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x0e, 0x0a,
	0x0a, 0x53, 0x45, 0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x45, 0x10, 0x09, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x44, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43, 0x54, 0x10, 0x0a, 0x12, 0x12,
	0x0a, 0x0e, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43, 0x54,
	0x10, 0x0b, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x50, 0x41, 0x53,
	0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x0c, 0x12, 0x2a, 0x0a, 0x26, 0x41, 0x43, 0x54, 0x49, 0x56,
	0x41, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x47, 0x4f, 0x4f,
	0x47, 0x4c, 0x45, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x4f,
	0x52, 0x10, 0x0d, 0x12, 0x2c, 0x0a, 0x28, 0x44, 0x45, 0x41, 0x43, 0x54, 0x49, 0x56, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x47, 0x4f, 0x4f, 0x47, 0x4c,
	0x45, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x4f, 0x52, 0x10,
	0x0e, 0x1a, 0xeb, 0x05, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f,
	0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06,
	0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e,
	0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x51, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x8f, 0x01, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x02,
	0x49, 0x64, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d,
	0x50, 0x54, 0x59, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x52, 0x4f, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x1a, 0xaf, 0x01,
	0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6e, 0x65, 0x78, 0x74, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x7e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x4e,
	0x45, 0x57, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x5f, 0x41,
	0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43, 0x54, 0x5f, 0x43,
	0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x04, 0x12, 0x10, 0x0a,
	0x0c, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43, 0x54, 0x5f, 0x46, 0x49, 0x4c, 0x4c, 0x10, 0x05, 0x1a,
	0x25, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x49, 0x64, 0x73, 0x1a, 0xe0, 0x02, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x15,
	0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x3a, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4c, 0x6f, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x1a, 0xe6, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x0a, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c,
	0x2e, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x66, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e,
	0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x11, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x1a, 0x5b, 0x0a, 0x0b, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x69, 0x63, 0x6f,
	0x6e, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44,
	0x10, 0x04, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_biconom_type_confirmation_proto_rawDescOnce sync.Once
	file_biconom_type_confirmation_proto_rawDescData = file_biconom_type_confirmation_proto_rawDesc
)

func file_biconom_type_confirmation_proto_rawDescGZIP() []byte {
	file_biconom_type_confirmation_proto_rawDescOnce.Do(func() {
		file_biconom_type_confirmation_proto_rawDescData = protoimpl.X.CompressGZIP(file_biconom_type_confirmation_proto_rawDescData)
	})
	return file_biconom_type_confirmation_proto_rawDescData
}

var file_biconom_type_confirmation_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_biconom_type_confirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_biconom_type_confirmation_proto_goTypes = []interface{}{
	(Confirmation_Status)(0),                // 0: biconom.type.Confirmation.Status
	(Confirmation_Method_Id)(0),             // 1: biconom.type.Confirmation.Method.Id
	(Confirmation_Field_Type)(0),            // 2: biconom.type.Confirmation.Field.Type
	(Confirmation_Field_Status_Id)(0),       // 3: biconom.type.Confirmation.Field.Status.Id
	(Confirmation_Log_Event_Type_Id)(0),     // 4: biconom.type.Confirmation.Log.Event.Type.Id
	(*Confirmation)(nil),                    // 5: biconom.type.Confirmation
	(*Confirmation_Id)(nil),                 // 6: biconom.type.Confirmation.Id
	(*Confirmation_Method)(nil),             // 7: biconom.type.Confirmation.Method
	(*Confirmation_Field)(nil),              // 8: biconom.type.Confirmation.Field
	(*Confirmation_Option)(nil),             // 9: biconom.type.Confirmation.Option
	(*Confirmation_Log)(nil),                // 10: biconom.type.Confirmation.Log
	nil,                                     // 11: biconom.type.Confirmation.FieldsEntry
	(*Confirmation_Field_Status)(nil),       // 12: biconom.type.Confirmation.Field.Status
	(*Confirmation_Field_Notification)(nil), // 13: biconom.type.Confirmation.Field.Notification
	(*Confirmation_Log_Event)(nil),          // 14: biconom.type.Confirmation.Log.Event
	(*Confirmation_Log_Event_Type)(nil),     // 15: biconom.type.Confirmation.Log.Event.Type
	(*contact.Contact)(nil),                 // 16: biconom.type.Contact
	(*anypb.Any)(nil),                       // 17: google.protobuf.Any
}
var file_biconom_type_confirmation_proto_depIdxs = []int32{
	1,  // 0: biconom.type.Confirmation.method_id:type_name -> biconom.type.Confirmation.Method.Id
	0,  // 1: biconom.type.Confirmation.status_id:type_name -> biconom.type.Confirmation.Status
	11, // 2: biconom.type.Confirmation.fields:type_name -> biconom.type.Confirmation.FieldsEntry
	9,  // 3: biconom.type.Confirmation.options:type_name -> biconom.type.Confirmation.Option
	1,  // 4: biconom.type.Confirmation.Method.method_id:type_name -> biconom.type.Confirmation.Method.Id
	2,  // 5: biconom.type.Confirmation.Field.type_id:type_name -> biconom.type.Confirmation.Field.Type
	12, // 6: biconom.type.Confirmation.Field.status:type_name -> biconom.type.Confirmation.Field.Status
	16, // 7: biconom.type.Confirmation.Field.contact:type_name -> biconom.type.Contact
	13, // 8: biconom.type.Confirmation.Field.notification:type_name -> biconom.type.Confirmation.Field.Notification
	14, // 9: biconom.type.Confirmation.Log.event:type_name -> biconom.type.Confirmation.Log.Event
	8,  // 10: biconom.type.Confirmation.FieldsEntry.value:type_name -> biconom.type.Confirmation.Field
	3,  // 11: biconom.type.Confirmation.Field.Status.id:type_name -> biconom.type.Confirmation.Field.Status.Id
	4,  // 12: biconom.type.Confirmation.Log.Event.event_type:type_name -> biconom.type.Confirmation.Log.Event.Type.Id
	17, // 13: biconom.type.Confirmation.Log.Event.data:type_name -> google.protobuf.Any
	4,  // 14: biconom.type.Confirmation.Log.Event.Type.event_type:type_name -> biconom.type.Confirmation.Log.Event.Type.Id
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_biconom_type_confirmation_proto_init() }
func file_biconom_type_confirmation_proto_init() {
	if File_biconom_type_confirmation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biconom_type_confirmation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Method); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Field_Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Field_Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Log_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biconom_type_confirmation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmation_Log_Event_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biconom_type_confirmation_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_biconom_type_confirmation_proto_goTypes,
		DependencyIndexes: file_biconom_type_confirmation_proto_depIdxs,
		EnumInfos:         file_biconom_type_confirmation_proto_enumTypes,
		MessageInfos:      file_biconom_type_confirmation_proto_msgTypes,
	}.Build()
	File_biconom_type_confirmation_proto = out.File
	file_biconom_type_confirmation_proto_rawDesc = nil
	file_biconom_type_confirmation_proto_goTypes = nil
	file_biconom_type_confirmation_proto_depIdxs = nil
}
